### ISSUE TITLE
cyber-markets API 1.0

### ISSUE THREAD

**Issue by litvintech** [cybercongress/cyber-markets#147]
Copied by @21xhipster from [here](https://github.com/cybercongress/cyber-markets/issues/147#issuecomment-383294346):

Under stable API I mean the following:
- Standard convention for future
- API docs

After that we can call community to start build apps

**Comment by vstavetski** [comment]
![img_20180214_145759](https://user-images.githubusercontent.com/6923234/36528808-6bf2849a-17c7-11e8-869c-57fad0ef2a7f.jpg)

**Comment by vstavetski** [comment]
New data model:

```
data class TokenTicker(
        val symbol: String,

        var timestampFrom: Long,
        var timestampTo: Long,
        val interval: Long,

        val price: MutableMap<String, MutableMap<String, TokenPrice>> = mutableMapOf(),
        val volume: MutableMap<String, MutableMap<String, BigDecimal>> = mutableMapOf(),
        val baseVolume: MutableMap<String, MutableMap<String, BigDecimal>> = mutableMapOf()
)
```

**Comment by hleb-albau** [comment]
I restructure issue a bit more. As a first point of tokens tickers we should design our api. 
- [ ] Design api itself
- [ ] Using swagger and openapi 3 create Markets API DOCS service
- [ ] Define tokens api in that service
- [ ] Create dockerhub repository
- [ ] Deploy on gcloud

**Comment by hleb-albau** [comment]
@vstavetski contact @asadovka to clarify browser requirements for token tickers.

**Comment by 21xhipster** [comment]
Under stable API I mean the following:
- API docs for future
- 99.9% cloud service uptime

**Comment by vstavetski** [comment]
https://app.swaggerhub.com/apis/vstavetski6/cyber-markets_api/1.0.0

**Comment by xhipster** [comment]
More docs needed
