### ISSUE TITLE
Store raw exchanges data

### ISSUE THREAD

**Issue by vstavetski** [cybercongress/cyber-markets#194]
implement a module that will save trades from the kafka topics and snapshots of orderbooks

**Comment by vstavetski** [comment]
- [ ] new module
- [ ] save trades
- [ ] save order book snapshots (default period - 10 min)
- [ ] refactor architecture for exchanges-connector sharding by exchanges
- [ ] api for raw data
- [ ] deploy to gcloud

**Comment by vstavetski** [comment]
Api definitions link:
https://app.swaggerhub.com/apis/vstavetski6/cyber-markets_api/1.0.0#/exchange/getExchangeInfo
